version: 0.2 
phases: 
  install: 
    runtime-versions: 
      nodejs: 12 
    commands: 
      - aws cloudformation package --template-file lambda-crud/template.yaml --s3-bucket venkat-build-artifacts-s3 --output-template-file outputTemplate.yaml 
artifacts: 
  files: 
    - template.yaml 
    - outputTemplate.yaml 
